### ISSUE TITLE
I have the following error with your code: CUDA

### ISSUE THREAD

**Issue by 106084** [mil-tokyo/bc_learning_image#1]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    main()
  File "main.py", line 19, in main
    chainer.cuda.get_device_from_id(opt.gpu).use()
  File "/home/user1/cjm/anaconda3/envs/bc/lib/python2.7/site-packages/chainer/cuda.py", line 164, in get_device_from_id
    check_cuda_available()
  File "/home/user1/cjm/anaconda3/envs/bc/lib/python2.7/site-packages/chainer/cuda.py", line 87, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up

**Comment by 106084** [comment]
But I have installed cudatoolkit8.0 and cudnn6.0
